# Generated by Django 5.2.10 on 2026-02-05 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('farmer_phone', models.CharField(max_length=15)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.crop')),
                ('problem_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.problemcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.village')),
            ],
        ),
        migrations.CreateModel(
            name='VisitAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('CROP', 'Crop Photo'), ('SOIL', 'Soil Photo'), ('BILL', 'Bill'), ('VOICE', 'Voice Note'), ('PDF', 'PDF Report'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='visit_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='visits.visit')),
            ],
        ),
    ]
