# Generated by Django 5.2.10 on 2026-01-29 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('CROP', 'Crop Photo'), ('SOIL', 'Soil Photo'), ('BILL', 'Bill'), ('VOICE', 'Voice Note'), ('PDF', 'PDF Report'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='visit_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='visits.visit')),
            ],
        ),
        migrations.DeleteModel(
            name='VisitImage',
        ),
    ]
