# Generated by Django 5.2.10 on 2026-02-24 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_populate_status_remove_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='visit_media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('bill', 'Bill'), ('audio', 'Audio'), ('video', 'Video')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='visits.visit')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
