# Generated by Django 5.2.10 on 2026-03-07 10:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_visit_media_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='farmer_phone',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='user',
        ),
        migrations.AddField(
            model_name='visit',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], db_index=True, default='pending', max_length=20),
        ),
    ]
