# Generated by Django 5.2.10 on 2026-03-09 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_cropissue_farmerfield_fieldcrop_recommendation_and_more'),
        ('visits', '0005_remove_visit_farmer_phone_remove_visit_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='masters.farmer'),
        ),
        migrations.AddField(
            model_name='visit',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='masters.farmerfield'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['farmer'], name='visits_visi_farmer__8ce3c2_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['employee'], name='visits_visi_employe_f25aa5_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['visit_date'], name='visits_visi_visit_d_61b894_idx'),
        ),
    ]
