# Generated by Django 5.2.10 on 2026-03-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_visit_farmer_visit_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='crop_condition',
            field=models.CharField(blank=True, default='', help_text='e.g. healthy, wilting, pest-affected, nutrient-deficient', max_length=30),
        ),
    ]
