# Generated by Django 5.2.10 on 2026-03-10 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_cropissue_status_farmerfield_created_by_employee_and_more'),
        ('visits', '0007_visit_crop_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='farmer_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='problem_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.problemcategory'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.village'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
