# Generated by Django 5.2.10 on 2026-03-10 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_cropissue_status_farmerfield_created_by_employee_and_more'),
        ('visits', '0008_alter_visit_farmer_name_alter_visit_problem_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('pending', 'Pending'), ('verified', 'Verified')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['visit_time'], name='visits_visi_visit_t_745292_idx'),
        ),
    ]
