# Generated by Django 5.2.10 on 2026-03-13 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_alter_farmerfield_options_and_more'),
        ('visits', '0009_visit_completed_time_alter_visit_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visit',
            name='visits_visi_visit_d_61b894_idx',
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='visits_visi_visit_t_745292_idx',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='visit_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='completed_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='field',
            new_name='land',
        ),
        migrations.AddField(
            model_name='visit',
            name='recommendations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('new', 'New'), ('followup', 'Followup')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.crop'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('pending', 'Pending'), ('verified', 'Verified')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(blank=True, help_text='Date of the visit', null=True),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['land'], name='visits_visi_land_id_061cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['crop'], name='visits_visi_crop_id_452e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['visit_type'], name='visits_visi_visit_t_34f26c_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status'], name='visits_visi_status_ae8d13_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['created_at'], name='visits_visi_created_7580ca_idx'),
        ),
    ]
