# Generated by Django 5.2.10 on 2026-03-23 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_remove_cropissue_problem_category_and_more'),
        ('visits', '0010_remove_visit_visits_visi_visit_d_61b894_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visit',
            name='visits_visi_farmer__8ce3c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='visits_visi_employe_f25aa5_idx',
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='visits_visi_land_id_061cd3_idx',
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='visits_visi_crop_id_452e6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='visits_visi_visit_t_34f26c_idx',
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='visits_visi_status_ae8d13_idx',
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='visits_visi_created_7580ca_idx',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='crop_condition',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='farmer_name',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='problem_category',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='village',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='visit_type',
        ),
        migrations.AlterField(
            model_name='visit',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visit',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='masters.farmer'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(),
        ),
    ]
