# Generated by Django 5.2.10 on 2026-03-24 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_village_district'),
        ('visits', '0011_remove_visit_visits_visi_farmer__8ce3c2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='land',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='start_time',
        ),
        migrations.AddField(
            model_name='visit',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='crop_health',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='crop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='crop_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='disease_issue',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.district'),
        ),
        migrations.AddField(
            model_name='visit',
            name='farmer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='farmer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='fertilizer_advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='follow_up_required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='general_advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='irrigation_advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='land_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='land_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='next_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='pest_issue',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='pesticide_advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.village'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='weed_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visit',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
