# Generated by Django 5.2.10 on 2026-03-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0012_remove_visit_end_time_remove_visit_farmer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='season',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='sowing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='variety',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
