# Generated by Django 5.2.10 on 2026-04-05 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0014_alter_crop_options_remove_crop_name'),
        ('visits', '0013_visit_season_visit_sowing_date_visit_variety'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='crop_name',
        ),
        migrations.AddField(
            model_name='visit',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='masters.crop'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='farmer_phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
