# Generated by Django 5.2.10 on 2026-04-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0014_remove_visit_crop_name_visit_crop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitmedia',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
