# Generated by Django 5.2.10 on 2026-05-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0020_visitattachment_evidence_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitattachment',
            options={'ordering': ['-uploaded_at', '-id']},
        ),
        migrations.AlterField(
            model_name='visitattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
