# Generated by Django 5.2.10 on 2026-05-30 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0018_performance_indexes'),
        ('visits', '0021_alter_visitattachment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['employee', 'created_at'], name='visits_visi_employe_0bc72b_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['employee', 'visit_date'], name='visits_visi_employe_321964_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['farmer', 'visit_date'], name='visits_visi_farmer__7b7729_idx'),
        ),
    ]
