# Generated by Django 5.2.10

from django.db import migrations, models


def backfill_field_notes_from_legacy(apps, schema_editor):
    Visit = apps.get_model("visits", "Visit")
    for visit in Visit.objects.iterator(chunk_size=500):
        notes = (visit.field_notes or "").strip()
        if notes:
            continue
        parts = []
        for attr in (
            "general_advice",
            "fertilizer_advice",
            "pesticide_advice",
            "irrigation_advice",
            "notes",
        ):
            val = (getattr(visit, attr, None) or "").strip()
            if val:
                parts.append(val)
        if not parts:
            continue
        combined = "\n".join(parts)
        visit.field_notes = combined
        if not (visit.observation or "").strip():
            visit.observation = combined
        visit.save(update_fields=["field_notes", "observation"])


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0022_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="action_taken",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="field_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="observation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="problem_seen",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_field_notes_from_legacy, migrations.RunPython.noop),
    ]
