# Generated by Django 5.2.10 on 2026-06-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0024_field_visit_problem_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='land_area',
            field=models.FloatField(blank=True, help_text='Acreage for this visit (canonical field visit acreage).', null=True),
        ),
    ]
