# Generated by Django 5.2.10 on 2026-06-19 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_duty_tracking_models'),
        ('visits', '0026_visit_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='duty_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='tracking.dutysession'),
        ),
        migrations.AddField(
            model_name='visit',
            name='workday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='tracking.workday'),
        ),
    ]
