# Generated by Django 5.2.17 on 2026-08-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0025_business_locations_and_multi_problem'),
        ('visits', '0029_visitmedia_canonical_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='problem_items',
            field=models.ManyToManyField(blank=True, help_text='Canonical multi-select problems for this visit.', related_name='visit_selections', to='masters.problemmaster'),
        ),
    ]
