# Generated by Django 5.2.10 on 2026-05-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('STATUS_CHANGE', 'Status Change'), ('UPLOAD', 'Upload'), ('PASSWORD_CHANGE', 'Password Change')], max_length=20),
        ),
    ]
