# Generated by Django 5.2.10 on 2026-03-09 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_farmer'),
        ('visits', '0005_remove_visit_farmer_phone_remove_visit_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmerField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=255)),
                ('field_size', models.DecimalField(blank=True, decimal_places=2, help_text='Field size in acres', max_digits=10, null=True)),
                ('soil_type', models.CharField(blank=True, choices=[('red', 'Red Soil'), ('black', 'Black Soil'), ('alluvial', 'Alluvial'), ('laterite', 'Laterite'), ('sandy', 'Sandy'), ('clay', 'Clay'), ('loamy', 'Loamy'), ('other', 'Other')], default='', max_length=20)),
                ('irrigation_type', models.CharField(blank=True, choices=[('rainfed', 'Rainfed'), ('borewell', 'Borewell'), ('canal', 'Canal'), ('drip', 'Drip'), ('sprinkler', 'Sprinkler'), ('other', 'Other')], default='', max_length=20)),
                ('gps_polygon', models.TextField(blank=True, default='', help_text='GeoJSON polygon or comma-separated lat,lng pairs')),
            ],
            options={
                'ordering': ['field_name'],
            },
        ),
        migrations.CreateModel(
            name='FieldCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.CharField(blank=True, choices=[('kharif', 'Kharif'), ('rabi', 'Rabi'), ('zaid', 'Zaid / Summer'), ('annual', 'Annual')], default='', max_length=20)),
                ('sowing_date', models.DateField(blank=True, null=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-sowing_date'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer', models.CharField(blank=True, default='', max_length=255)),
                ('pesticide', models.CharField(blank=True, default='', max_length=255)),
                ('dosage', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='farmer',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='farmer',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_farmers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmer',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='masters.district'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='farmer_code',
            field=models.CharField(blank=True, db_index=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='gps_location',
            field=models.CharField(blank=True, default='', help_text='Lat,Lng e.g. 12.345678,79.123456', max_length=50),
        ),
        migrations.AddField(
            model_name='farmer',
            name='irrigation_type',
            field=models.CharField(blank=True, choices=[('rainfed', 'Rainfed'), ('borewell', 'Borewell'), ('canal', 'Canal'), ('drip', 'Drip'), ('sprinkler', 'Sprinkler'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='farmer',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('red', 'Red Soil'), ('black', 'Black Soil'), ('alluvial', 'Alluvial'), ('laterite', 'Laterite'), ('sandy', 'Sandy'), ('clay', 'Clay'), ('loamy', 'Loamy'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='farmer',
            name='taluk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='masters.taluk'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='total_land_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total land area in acres', max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['farmer_code'], name='masters_far_farmer__6916b8_idx'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['assigned_employee'], name='masters_far_assigne_67dd68_idx'),
        ),
        migrations.AddField(
            model_name='cropissue',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='masters.crop'),
        ),
        migrations.AddField(
            model_name='cropissue',
            name='problem_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crop_issues', to='masters.problemcategory'),
        ),
        migrations.AddField(
            model_name='cropissue',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='farmerfield',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='masters.farmer'),
        ),
        migrations.AddField(
            model_name='fieldcrop',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_crops', to='masters.crop'),
        ),
        migrations.AddField(
            model_name='fieldcrop',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='masters.farmerfield'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='masters.cropissue'),
        ),
    ]
