# Generated by Django 5.2.10 on 2026-03-09 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0003_cropissue_farmerfield_fieldcrop_recommendation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmerActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("FARMER_CREATED", "Farmer Created"),
                            ("VISIT_COMPLETED", "Visit Completed"),
                            ("ISSUE_REPORTED", "Issue Reported"),
                            ("RECOMMENDATION_GIVEN", "Recommendation Given"),
                            ("FOLLOWUP_VISIT", "Follow-up Visit"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "reference_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of the related object (Visit, CropIssue, etc.)",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Farmer activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="crop",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="district",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="taluk",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="village",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="crop",
            name="crop_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cereal", "Cereal"),
                    ("pulse", "Pulse"),
                    ("oilseed", "Oilseed"),
                    ("vegetable", "Vegetable"),
                    ("fruit", "Fruit"),
                    ("spice", "Spice"),
                    ("fiber", "Fiber"),
                    ("commercial", "Commercial"),
                    ("other", "Other"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="scientific_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="crop",
            name="typical_season",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kharif", "Kharif"),
                    ("rabi", "Rabi"),
                    ("zaid", "Zaid / Summer"),
                    ("annual", "Annual"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="crop",
                    name="name",
                    field=models.CharField(max_length=255, unique=True),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="district",
                    name="name",
                    field=models.CharField(max_length=255, unique=True),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddIndex(
            model_name="taluk",
            index=models.Index(
                fields=["district"], name="masters_tal_distric_e6dcd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="village",
            index=models.Index(fields=["taluk"], name="masters_vil_taluk_i_48909e_idx"),
        ),
        migrations.AddField(
            model_name="farmeractivity",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="farmer_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="farmeractivity",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="masters.farmer",
            ),
        ),
        migrations.AddIndex(
            model_name="farmeractivity",
            index=models.Index(
                fields=["farmer"], name="masters_far_farmer__bc2d74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmeractivity",
            index=models.Index(
                fields=["created_at"], name="masters_far_created_966f1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmeractivity",
            index=models.Index(
                fields=["farmer", "activity_type"],
                name="masters_far_farmer__1819e2_idx",
            ),
        ),
    ]
