# Generated by Django 5.2.10 on 2026-03-13 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_cropissue_status_farmerfield_created_by_employee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmerfield',
            options={'ordering': ['land_name']},
        ),
        migrations.RenameField(
            model_name='farmerfield',
            old_name='field_name',
            new_name='land_name',
        ),
        migrations.RenameField(
            model_name='fieldcrop',
            old_name='field',
            new_name='land',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='farmerfield',
            name='field_size',
        ),
        migrations.RemoveField(
            model_name='farmerfield',
            name='gps_polygon',
        ),
        migrations.RemoveField(
            model_name='fieldcrop',
            name='expected_harvest_date',
        ),
        migrations.RemoveField(
            model_name='fieldcrop',
            name='season',
        ),
        migrations.AddField(
            model_name='farmer',
            name='created_by_employee',
            field=models.ForeignKey(blank=True, help_text='Employee who created the farmer record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_farmers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmerfield',
            name='gps_location',
            field=models.CharField(blank=True, default='', help_text='Lat,Lng or GeoJSON polygon', max_length=255),
        ),
        migrations.AddField(
            model_name='farmerfield',
            name='land_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Land size in acres', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fieldcrop',
            name='crop_name',
            field=models.CharField(default='Unknown Crop', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldcrop',
            name='crop_stage',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmerfield',
            name='created_by_employee',
            field=models.ForeignKey(blank=True, help_text='Employee who created the land record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fields', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldcrop',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_crops', to='masters.crop'),
        ),
    ]
