# Generated by Django 5.2.10 on 2026-03-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_alter_farmerfield_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='village',
            name='masters_vil_taluk_i_48909e_idx',
        ),
        migrations.RemoveField(
            model_name='village',
            name='taluk',
        ),
    ]
