# Generated by Django 5.2.10 on 2026-03-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_remove_village_masters_vil_taluk_i_48909e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropissue',
            name='problem_category',
        ),
        migrations.RemoveField(
            model_name='taluk',
            name='district',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='taluk',
        ),
    ]
