# Generated by Django 5.2.10 on 2026-03-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_remove_cropissue_problem_category_and_more'),
        ('visits', '0011_remove_visit_visits_visi_farmer__8ce3c2_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProblemCategory',
        ),
        migrations.DeleteModel(
            name='Taluk',
        ),
    ]
