# Generated by Django 5.2.10 on 2026-03-24 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_delete_problemcategory_delete_taluk'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='villages', to='masters.district'),
        ),
    ]
