# Generated by Django 5.2.10 on 2026-03-24 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_village_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmeractivity',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='masters.farmer'),
        ),
    ]
