# Generated by Django 5.2.10 on 2026-03-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_make_crop_names_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['name_en']},
        ),
        migrations.RemoveField(
            model_name='crop',
            name='name',
        ),
    ]
