# Generated by Django 5.2.10 on 2026-05-30 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0017_farmer_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['phone'], name='masters_far_phone_aa3869_idx'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['is_active', 'name'], name='masters_far_is_acti_307e04_idx'),
        ),
    ]
