# Generated by Django 5.2.10 on 2026-06-11 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0021_problemmaster_tamil_name'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='problemmaster',
            new_name='masters_pro_categor_8de110_idx',
            old_name='masters_pro_categor_a8f2c1_idx',
        ),
        migrations.RenameIndex(
            model_name='problemmaster',
            new_name='masters_pro_crop_id_4b6c35_idx',
            old_name='masters_pro_crop_id_91b4e2_idx',
        ),
    ]
