# Generated by Django 5.2.17 on 2026-08-17 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0024_farmer_source_quarter_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='firka_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='village',
            name='official_code',
            field=models.CharField(blank=True, default='', help_text='Official revenue village code when supplied by source PDF.', max_length=32),
        ),
        migrations.AddField(
            model_name='village',
            name='official_source',
            field=models.URLField(blank=True, default='', help_text='Official PDF/page URL for this village row.', max_length=500),
        ),
        migrations.AlterField(
            model_name='problemmaster',
            name='crop',
            field=models.ForeignKey(blank=True, help_text='Legacy single-crop limit. Prefer crops/CropProblem for new data.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_masters', to='masters.crop'),
        ),
        migrations.CreateModel(
            name='CropProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_problems', to='masters.crop')),
                ('problem_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_problems', to='masters.problemmaster')),
            ],
        ),
        migrations.AddField(
            model_name='problemmaster',
            name='crops',
            field=models.ManyToManyField(blank=True, help_text='Canonical multi-crop mappings for this problem.', related_name='problem_items', through='masters.CropProblem', to='masters.crop'),
        ),
        migrations.CreateModel(
            name='Taluk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taluks', to='masters.district')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='farmer',
            name='taluk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='masters.taluk'),
        ),
        migrations.AddField(
            model_name='village',
            name='taluk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='villages', to='masters.taluk'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['taluk', 'is_active'], name='masters_vil_taluk_i_8a9ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['district', 'is_active'], name='masters_vil_distric_ab5f37_idx'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['taluk', 'official_code'], name='masters_vil_taluk_i_7c7400_idx'),
        ),
        migrations.AddConstraint(
            model_name='village',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('official_code', ''), _negated=True), ('taluk__isnull', False)), fields=('taluk', 'official_code'), name='uniq_village_taluk_official_code'),
        ),
        migrations.AddIndex(
            model_name='cropproblem',
            index=models.Index(fields=['crop', 'problem_master'], name='masters_cro_crop_id_1a74a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='cropproblem',
            constraint=models.UniqueConstraint(fields=('problem_master', 'crop'), name='uniq_crop_problem_master_crop'),
        ),
        migrations.AddIndex(
            model_name='taluk',
            index=models.Index(fields=['district', 'is_active'], name='masters_tal_distric_ab9fdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='taluk',
            constraint=models.UniqueConstraint(fields=('district', 'name'), name='uniq_taluk_district_name'),
        ),
    ]
