# Generated by Django 5.2.17 on 2026-08-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0025_business_locations_and_multi_problem'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='village',
            name='uniq_village_taluk_official_code',
        ),
        migrations.AddConstraint(
            model_name='village',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('official_code', ''), _negated=True), ('taluk__isnull', False)), fields=('taluk', 'official_code', 'name'), name='uniq_village_taluk_code_name'),
        ),
    ]
