# Generated by Django 5.2.10 on 2026-03-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employeeprofile_role_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='can_login',
            field=models.BooleanField(default=True),
        ),
    ]
