# Generated by Django 5.2.10 on 2026-05-29 06:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_employeeprofile_profile_photo_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=120, null=True)),
                ('device_model', models.CharField(blank=True, max_length=120, null=True)),
                ('platform', models.CharField(blank=True, max_length=40, null=True)),
                ('app_version', models.CharField(blank=True, max_length=40, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_login_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_login_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_em_user_id_a36ec9_idx')],
            },
        ),
    ]
