# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_employeedevicesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='active_device_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='mobile_session_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeedevicesession',
            name='active_device_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeedevicesession',
            name='session_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
