# Generated by Django 5.2.10 on 2026-05-30 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_device_session_version_fields'),
        ('masters', '0018_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['is_active_employee'], name='accounts_em_is_acti_c25ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['is_active_employee', 'district'], name='accounts_em_is_acti_e964c9_idx'),
        ),
    ]
