# Generated by Django 5.2.10 on 2026-05-31 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_admin_security'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminsession',
            new_name='accounts_ad_user_id_7dfc9e_idx',
            old_name='accounts_ad_user_id_7a0fae_idx',
        ),
    ]
