# Generated by Django 5.2.17 on 2026-08-17 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_accounts_ad_user_id_7a0fae_idx_accounts_ad_user_id_7dfc9e_idx'),
        ('masters', '0026_village_identity_code_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLocationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_location_assignments', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_location_assignments', to='masters.district')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_assignments', to='accounts.employeeprofile')),
                ('taluk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_location_assignments', to='masters.taluk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_employee_location_assignments', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_location_assignments', to='masters.village')),
            ],
            options={
                'ordering': ['employee', 'district', 'taluk', 'village'],
                'indexes': [models.Index(fields=['employee', 'is_active'], name='accounts_em_employe_17b76f_idx'), models.Index(fields=['district', 'is_active'], name='accounts_em_distric_d8a7a1_idx'), models.Index(fields=['taluk', 'is_active'], name='accounts_em_taluk_i_d1781e_idx'), models.Index(fields=['village', 'is_active'], name='accounts_em_village_e621be_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'district', 'taluk', 'village'), name='uniq_employee_location_assignment', nulls_distinct=False)],
            },
        ),
    ]
