# Generated by Django 5.2.10 on 2026-04-08 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('visit_summary', 'Visit Summary'), ('employee_performance', 'Employee Performance'), ('village_summary', 'Village Summary'), ('farmer_history', 'Farmer History'), ('daily_summary', 'Daily Summary'), ('monthly_summary', 'Monthly Summary')], max_length=50)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Filter params used')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('file_url', models.URLField(blank=True, default='', max_length=1000)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requested_by', 'status'], name='reports_rep_request_bd21d8_idx'), models.Index(fields=['report_type'], name='reports_rep_report__dbb097_idx')],
            },
        ),
    ]
