# Generated by Django 5.2.10 on 2026-02-05 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to=settings.AUTH_USER_MODEL)),
                ('workday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tracking.workday')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GPS_OFF', 'GPS Off'), ('OFFLINE', 'Offline'), ('APP_OFF', 'App Closed')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_events', to=settings.AUTH_USER_MODEL)),
                ('workday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_events', to='tracking.workday')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='workday',
            index=models.Index(fields=['user', 'date'], name='tracking_wo_user_id_0f43a1_idx'),
        ),
        migrations.AddIndex(
            model_name='workday',
            index=models.Index(fields=['is_active'], name='tracking_wo_is_acti_582a31_idx'),
        ),
        migrations.AddIndex(
            model_name='locationlog',
            index=models.Index(fields=['user', 'recorded_at'], name='tracking_lo_user_id_c74477_idx'),
        ),
    ]
