# Generated by Django 5.2.10 on 2026-02-23 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_distance_km', models.FloatField(default=0)),
                ('total_duration_seconds', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('gps_issues_count', models.IntegerField(default=0)),
                ('suspicious_points', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='locationlog',
            name='app_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='locationlog',
            name='battery_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationlog',
            name='device_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locationlog',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationlog',
            name='network_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='locationlog',
            index=models.Index(fields=['recorded_at'], name='tracking_lo_recorde_6fa022_idx'),
        ),
        migrations.AddField(
            model_name='employeedailysummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='employeedailysummary',
            unique_together={('user', 'date')},
        ),
    ]
