# Generated by Django 5.2.10 on 2026-01-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_availabilityevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
