# Generated by Django 5.2.10 on 2026-03-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_worklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Start latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='workday',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Start longitude', max_digits=9, null=True),
        ),
    ]
