# Generated by Django 5.2.10 on 2026-05-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_workday_auto_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationlog',
            name='heading',
            field=models.FloatField(blank=True, help_text='Heading/bearing in degrees when provided by the device', null=True),
        ),
        migrations.AddField(
            model_name='locationlog',
            name='speed',
            field=models.FloatField(blank=True, help_text='Speed in km/h when provided by the device', null=True),
        ),
    ]
