# Generated by Django 5.2.10 on 2026-05-30 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_locationlog_speed_heading'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='locationlog',
            index=models.Index(fields=['workday', 'recorded_at'], name='tracking_lo_workday_99774f_idx'),
        ),
        migrations.AddIndex(
            model_name='workday',
            index=models.Index(fields=['user', 'is_active'], name='tracking_wo_user_id_36bcfe_idx'),
        ),
        migrations.AddIndex(
            model_name='workday',
            index=models.Index(fields=['date', 'is_active'], name='tracking_wo_date_474ce4_idx'),
        ),
    ]
