# Generated by Django 5.2.7 on 2026-06-19 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('auto_ended', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_sessions', to=settings.AUTH_USER_MODEL)),
                ('workday', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_session', to='tracking.workday')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duty_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_snapshots', to='tracking.dutysession')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('point_type', models.CharField(choices=[('gps', 'GPS'), ('visit', 'Visit'), ('farmer', 'Farmer')], default='gps', max_length=10)),
                ('visit_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('farmer_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_permanent', models.BooleanField(default=False, help_text='True for visit/farmer stops — never throttled or deduplicated away.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duty_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='tracking.dutysession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['recorded_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='dutysession',
            index=models.Index(fields=['user', 'date'], name='tracking_du_user_id_d3c233_idx'),
        ),
        migrations.AddIndex(
            model_name='dutysession',
            index=models.Index(fields=['user', 'is_active'], name='tracking_du_user_id_0877b0_idx'),
        ),
        migrations.AddIndex(
            model_name='dutysession',
            index=models.Index(fields=['date', 'is_active'], name='tracking_du_date_3bf502_idx'),
        ),
        migrations.AddIndex(
            model_name='employeelivelocation',
            index=models.Index(fields=['recorded_at'], name='tracking_em_recorde_b78d47_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeroutepoint',
            index=models.Index(fields=['user', 'recorded_at'], name='tracking_em_user_id_772fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeroutepoint',
            index=models.Index(fields=['duty_session', 'recorded_at'], name='tracking_em_duty_se_b6f100_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeroutepoint',
            index=models.Index(fields=['user', 'point_type', 'recorded_at'], name='tracking_em_user_id_deff15_idx'),
        ),
    ]
