# Generated by Django 5.2.7 on 2026-07-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_employeeroutepoint_client_point_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeroutepoint',
            name='point_type',
            field=models.CharField(choices=[('gps', 'GPS'), ('visit', 'Visit'), ('farmer', 'Farmer'), ('start', 'Workday start'), ('end', 'Workday end')], default='gps', max_length=10),
        ),
    ]
