# Generated by Django 5.2.10 on 2026-07-23 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_route_point_start_end_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelivelocation',
            name='app_state',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='employeelivelocation',
            name='last_client_heartbeat_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeelivelocation',
            name='last_client_point_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeelivelocation',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='employeelivelocation',
            name='network_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeelivelocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='employeelivelocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='employeelivelocation',
            name='recorded_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='employeelivelocation',
            index=models.Index(fields=['last_heartbeat_at'], name='tracking_em_last_he_0ebcd3_idx'),
        ),
        migrations.AddIndex(
            model_name='employeelivelocation',
            index=models.Index(fields=['duty_session', 'last_heartbeat_at'], name='tracking_em_duty_se_eb04bb_idx'),
        ),
    ]
